# Generated by Django 5.1.15 on 2026-07-04 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('veille_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('raw_content', models.TextField()),
                ('cleaned_content', models.TextField(blank=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='veille_sessions.veillesession')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sources.source')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'is_duplicate'], name='scraping_ra_session_c935f5_idx'), models.Index(fields=['category'], name='scraping_ra_categor_d88fc9_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'content_hash'), name='uniq_doc_per_session')],
            },
        ),
    ]
