# Generated by Django 5.1.15 on 2026-07-04 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veille_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('markdown', 'Markdown'), ('pdf', 'PDF'), ('html', 'HTML')], default='markdown', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('content_markdown', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='deliverables/%Y/%m/')),
                ('sources_cited', models.JSONField(default=list)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='veille_sessions.veillesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
