# Generated by Django 5.1.15 on 2026-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tweet_id', models.CharField(max_length=40, unique=True)),
                ('author_handle', models.CharField(max_length=100)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('url', models.URLField(max_length=300)),
                ('posted_at', models.DateTimeField(db_index=True)),
                ('metrics', models.JSONField(default=dict)),
                ('lang', models.CharField(blank=True, max_length=8)),
                ('matched_query', models.CharField(blank=True, max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('themes', models.ManyToManyField(related_name='tweets', to='themes.theme')),
            ],
            options={
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['posted_at'], name='twitter_twe_posted__e7da63_idx'), models.Index(fields=['fetched_at'], name='twitter_twe_fetched_d9748d_idx')],
            },
        ),
    ]
