# Generated by Django 5.1.15 on 2026-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_llm_provider', models.CharField(choices=[('claude', 'Claude'), ('openai', 'OpenAI'), ('mistral', 'Mistral'), ('ollama', 'Ollama'), ('fake', 'Fake')], default='claude', max_length=20)),
                ('active_llm_model', models.CharField(default='claude-sonnet-4', max_length=80)),
                ('fallback_llm_provider', models.CharField(blank=True, default='', max_length=20)),
                ('max_documents_per_session', models.PositiveIntegerField(default=30)),
                ('max_sources_per_spontaneous', models.PositiveIntegerField(default=8)),
                ('default_deliverable_format', models.CharField(choices=[('markdown', 'Markdown'), ('pdf', 'PDF'), ('html', 'HTML')], default='markdown', max_length=10)),
                ('global_rate_limit_seconds', models.PositiveIntegerField(default=2)),
                ('twitter_enabled', models.BooleanField(default=False)),
                ('twitter_display_delay_hours', models.PositiveIntegerField(default=24)),
            ],
            options={
                'verbose_name': 'App Configuration',
                'verbose_name_plural': 'App Configuration',
            },
        ),
    ]
