# Generated by Django 5.1.15 on 2026-07-04 04:02

import apps.configuration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='provider_api_base_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='active_llm_model',
            field=models.CharField(default=apps.configuration.models._default_active_llm_model, max_length=80),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='active_llm_provider',
            field=models.CharField(choices=[('claude', 'Claude'), ('openai', 'OpenAI'), ('mistral', 'Mistral'), ('ollama', 'Ollama'), ('fake', 'Fake')], default=apps.configuration.models._default_active_llm_provider, max_length=20),
        ),
    ]
