# Generated by Django 5.1.15 on 2026-07-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_appconfiguration_provider_api_base_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfiguration',
            name='twitter_display_delay_hours',
        ),
        migrations.RemoveField(
            model_name='appconfiguration',
            name='twitter_enabled',
        ),
    ]
