# Generated by Django 5.1.15 on 2026-07-04 02:39

import apps.veille_sessions.states
import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeilleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('permanent', 'Permanent'), ('spontaneous', 'Spontaneous')], max_length=12)),
                ('free_topic', models.CharField(blank=True, max_length=300)),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('categorizing', 'Categorizing'), ('summarizing', 'Summarizing'), ('generating', 'Generating'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=50)),
                ('status_message', models.TextField(blank=True)),
                ('llm_provider', models.CharField(blank=True, max_length=20)),
                ('llm_model', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(default=dict)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='themes.theme')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='veille_sess_status_f11f84_idx'), models.Index(fields=['mode'], name='veille_sess_mode_0ccaf6_idx'), models.Index(fields=['theme', '-created_at'], name='veille_sess_theme_i_af90c5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('mode', 'permanent'), ('theme__isnull', False)), models.Q(('free_topic__gt', ''), ('mode', 'spontaneous')), _connector='OR'), name='session_mode_theme_or_topic')],
            },
            bases=(apps.veille_sessions.states.VeilleSessionTransitionsMixin, models.Model),
        ),
    ]
