# Generated by Django 5.1.15 on 2026-07-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veille_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('categorizing', 'Categorizing'), ('summarizing', 'Summarizing'), ('generating', 'Generating'), ('done', 'Done'), ('error', 'Error')], max_length=20)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='veille_sessions.veillesession')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='veille_sess_session_16441c_idx')],
            },
        ),
    ]
