# Generated by Django 5.1.15 on 2026-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('html', 'HTML'), ('api', 'API'), ('sitemap', 'Sitemap')], max_length=20)),
                ('selector_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reliability_score', models.PositiveSmallIntegerField(default=50)),
                ('rate_limit_seconds', models.PositiveIntegerField(default=2)),
                ('requires_js', models.BooleanField(default=False)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('never', 'Never'), ('ok', 'Ok'), ('error', 'Error')], default='never', max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'source_type'], name='sources_sou_is_acti_eded58_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reliability_score__lte', 100)), name='src_score_max')],
            },
        ),
    ]
