# Generated by Django 5.1.15 on 2026-07-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='article_url_pattern',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='discovery_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='feed_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='source',
            name='last_item_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='sitemap_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
