# Generated by Django 5.1.15 on 2026-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('manual', 'Manual')], default='daily', max_length=10)),
                ('window_strategy', models.CharField(choices=[('since_last_run', 'Since Last Run'), ('calendar_day', 'Calendar Day'), ('rolling', 'Rolling')], default='since_last_run', max_length=16)),
                ('preferred_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lookback_hours', models.PositiveIntegerField(default=24)),
                ('keep_undated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('llm_categories', models.JSONField(default=list)),
                ('twitter_enabled', models.BooleanField(default=False)),
                ('twitter_queries', models.JSONField(default=list)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('sources', models.ManyToManyField(blank=True, related_name='themes', to='sources.source')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='themes_them_is_acti_75e677_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('preferred_hour__lte', 23)), name='theme_hour_max')],
            },
        ),
    ]
