# Generated by Django 5.1.15 on 2026-07-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='twitter_enabled',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='twitter_queries',
        ),
    ]
