# Generated by Django 5.1.15 on 2026-07-04 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veille_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=80)),
                ('operation', models.CharField(choices=[('organize', 'Organize'), ('categorize', 'Categorize'), ('summarize', 'Summarize'), ('compose', 'Compose')], max_length=20)),
                ('prompt_version', models.CharField(max_length=20)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='veille_sessions.veillesession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider'], name='llm_orchest_provide_2bb1f8_idx'), models.Index(fields=['operation'], name='llm_orchest_operati_8a5446_idx'), models.Index(fields=['created_at'], name='llm_orchest_created_28d528_idx')],
            },
        ),
    ]
